name: Plugin CI
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  quality:
    uses: quadcore-factory/plugin-factory-ci/.github/workflows/reusable-plugin-quality.yml@v1.0.2
    with:
      php-version: '8.3'
  package:
    needs: quality
    uses: quadcore-factory/plugin-factory-ci/.github/workflows/reusable-plugin-package.yml@v1.0.2
    with:
      package-name: landing-bird-scheduler
      include-vendor: false
